# basic options
title: Hackerrank exercises
author: Steven Barnes
email: slbcr@yahoo.com
description: Collection of coding solutions for exercises on hackerrank
github_username:  slbccfl
theme: jekyll-theme-hacker

source: docs
destination: docs/_site

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker

collections:
  solutions:
    output: true
    
