# basic options
title: Hackerrank exercises
author: Steven Barnes
email: slbcr@yahoo.com
description: Collection of coding solutions for exercises on hackerrank
github_username:  slbccfl
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
